skip_local_validator = true

[toolchain]
solana_version = "1.18.18"
anchor_version = "0.29.0"
[features]
resolution = true
skip-lint = false

[programs.localnet]
egggame = "6XTwUGq2v8zJ2Uy3EhgPiWuwvtcX2gzs4z5UBhMBDcEA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
